### ISSUE TITLE
IOCONCLKDIV0 to IOCONCLKDIV5 are missing from SYSCON

### ISSUE THREAD

**Issue by Samonitari** [lpc-rs/lpc82x-pac#22]
Hi!

Thank you for your work! Skip to the next paragraph for the issue!
I also started this project (just a bit before you uploaded it xD), but I did not have the time to create the crate and maintain it since. Also I did not notice, the field size issue. Glad you spotted it!
Soon I am getting to the point slowly when I start programming (custom board design takes some time), so time to prepare the chip crate, **this time for real**
 
I did open the generated rust code, and I think this _issue_ stands with it.
[LPC824 Glitch Filter Clock Divide Register Issue](https://community.nxp.com/thread/422021)

**Comment by hannobraun** [comment]
Hi @Samonitari,

thanks for reporting this issue, and thank you for your kind words.

In fact, it seems like the IOCONCLKDIV6 register is in the right place, but all the other ones are just missing. This should be easy enough to fix, by adding the other registers to the SVD file. I'm currently busy with other things, so it will be a few weeks until I get to this issue. Is this fine with you? I can squeeze it in earlier, if you're in a hurry.

By the way, would you mind talking about what you're working on? You don't have to of course, I'm just always curious what people are doing with embedded Rust. Feel free to hit me up at hanno@braun-robotics.com, if you feel it would be off-topic here.

**Comment by Samonitari** [comment]
I am still debating on using RC filter or the built in glitch filter for button debounce, but I would like it to be included. Do you have experience on the latter? I would be glad to left off those resistor-capacitance pairs from the design (currently those are in place).

Also, did you receive any replies from NXP regarding the various upstream issues?

**Comment by hannobraun** [comment]
> I am still debating on using RC filter or the built in glitch filter for button debounce, but I would like it to be included. Do you have experience on the latter? I would be glad to left off those resistor-capacitance pairs from the design (currently those are in place).

No, I haven't used it yet.

> Also, did you receive any replies from NXP regarding the various upstream issues?

I haven't submitted them yet. It's on my list, but there's so much stuff to do. I'm currently working on a higher-level API for LPC82x (will be released next week, unless something goes horribly wrong). I hope I can get back to this project soon after.

**Comment by hannobraun** [comment]
Oops, I accidentally closed this. It's fixed in the code now, but this issue should stay open until it's also fixed upstream.

**Comment by hannobraun** [comment]
I've reported this issue to NXP: https://community.nxp.com/thread/465465

**Comment by hannobraun** [comment]
Migrated this issue to the new repository: https://github.com/lpc-rs/lpc-pac/issues/20
